name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: amake/innosetup
      options: --user root

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Permission to xclient
      run: chmod -R 777 /home/xclient/.wine

    - name: Change .wine ownership to root
      run:  chown -R root /home/xclient/.wine

    - name: Install packages
      run: apt update -y && apt install wget -y && apt install unzip -y

    - name: Download zip files
      run: wget https://github.com/HexmosTech/Lama2/releases/download/v1.5.7/l2-v1.5.7-windows-amd64.zip

    - name: Unzip windows installer
      run: unzip l2-v1.5.7-windows-amd64.zip -d inno/

    - name: Build exe
      run: cd inno && iscc LamaInno.iss && ls -l

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: windows-x64-lama2.exe
        path: inno/mysetup.exe
        retention-days: 5



