name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: amake/innosetup
      options: --user root

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Permission to xclient
      run: chmod -R 777 /home/xclient/.wine

    - name: Change .wine ownership to root
      run:  chown -R root /home/xclient/.wine

    - name: Install packages
      run: apt update -y && apt install wget -y && apt install unzip -y && apt install python3 -y

    - name: Run python code
      run: | 
          python3 -c "
          import struct
          import json
          import http.client
      
          def get_file():
              conn = http.client.HTTPSConnection('api.github.com')
              payload = ''
              headers = {
                  'User-Agent': 'Hexmos'
              }
              conn.request('GET', '/repos/HexmosTech/Lama2/releases/latest', payload, headers)
              res = conn.getresponse()
              data = res.read()
              return json.loads(data.decode('utf-8'))

          def get_platform():
              return 'amd64'

          def search(files, platform):
              search_string = 'windows-' + platform
              for row in files['assets']:
                  if search_string in row['name'] and 'md5' not in row['name']:
                      return row['browser_download_url']            

          def main():
              files = get_file()
              platform = get_platform()
              download_link = search(files, platform)
              return download_link

          if __name__ == '__main__':
              link = main()
              print(link)" | wget -P inno/64 -i -
              

    - name: Unzip windows installer
      run: cd inno/64 && unzip *.zip -d .

    - name: Build exe
      run: cd inno && iscc LamaInno.iss && ls -l

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: windows-x64-lama2.exe
        path: inno/mysetup.exe
        retention-days: 5



