name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: amake/innosetup
      options: --user root

    steps:

    - name: Build Docker image
      run: ls -l
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test checkout
      run: ls -l

    - name: Install packages
      run: apt update -y && apt install wget -y && apt install unzip -y

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag lama2/wget

    - name: Run Docker container
      run: docker run --volume "${{ github.workspace }}:/work" lama2/wget
