name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: amake/innosetup
      options: --user root

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install packages
      run: apt update -y && apt install wget -y && apt install unzip -y

    - name: Download zip files
      run: wget https://github.com/HexmosTech/Lama2/releases/download/v1.5.7/l2-v1.5.7-windows-amd64.zip

    - name: Unzip windows installer
      run: unzip l2-v1.5.7-windows-amd64.zip -d inno/

    - name: cd to inno folder
      run: cd inno && ls -l

    - name: List files inside inno
      run: ls -l 


