name: Build on Windows
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      -  run: |
          $lamaUrl = python -c "
          import struct
          import json
          import http.client

          def get_file():
              conn = http.client.HTTPSConnection('api.github.com')
              payload = ''
              headers = {
                  'User-Agent': 'Hexmos'
              }
              conn.request('GET', '/repos/HexmosTech/Lama2/releases/latest', payload, headers)
              res = conn.getresponse()
              data = res.read()
              return json.loads(data.decode('utf-8'))

          def get_platform():
              platform = 8*struct.calcsize('P')
              return 'amd64' if platform == 64 else '386'

          def search(files, platform):
              search_string = 'windows-' + platform
              for row in files['assets']:
                  if search_string in row['name'] and 'md5' not in row['name']:
                      return row['browser_download_url']            

          def main():
              files = get_file()
              platform = get_platform()
              download_link = search(files, platform)
              return download_link

          if __name__ == '__main__':
              link = main()
              print(link)
          " | Out-String
          choco install wget -y
          wget $lamaUrl
          choco apikey --key  ${{ secrets.CHOCOLATELY_API_TOKEN }} --source https://push.chocolatey.org/
          choco push <package_name>.nupkg --source https://push.chocolatey.org/
                                      
